#!/bin/bash

set -euo pipefail

if [ $# -ne 2 ]
then
 echo "usage: $0 <DNS record> <domain>"
 exit 1
fi

now=$(date +"%Y%m%dT%H%M")
record="$1"
domain="$2"

filename="/root/dig-test/results/$domain-$now-$record.txt"

echo "$now" > "$filename"
dig "$record" +noadditional +noquestion +nocomments +nocmd +nostats $domain. @1.1.1.1 >> "$filename"
